cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'caskroom/cask'

#brew 'ack'
#brew 'coreutils'
brew 'awscli'
brew 'antigen'
brew 'git'
brew 'go'
brew 'grc'
brew 'hub'
#brew 'imagemagick'
#brew 'jp2a'
#brew 'jq'
#brew 'libcaca', args: ['with-imlib2']
#brew 'libgit2'
brew 'mkcert'
brew 'openssl'
brew 'node'
#brew 'readline'
brew 'pip-completion'
#brew 'postgresql'
#brew 'puma/puma/puma-dev'
brew 'python'
brew 'python3'
#brew 'ruby-build'
brew 'rbenv'
#brew 'roundup'
brew 'ssh-copy-id'
brew 'spaceman-diff'
#brew 'spark'
#brew 'unrar'
brew 'watchman'
brew 'wget'
brew 'yarn'
#brew 'youtube-dl'
brew 'zsh'

# cask '1password'
# cask 'adium'
cask 'atom'
cask 'arq'
cask 'alfred'
cask 'boostnote'
#cask 'firefox'
#cask 'garmin-express'
cask 'google-chrome'
cask 'iTerm2'
cask 'react-native-debugger'
cask 'slack'
#cask 'sublime-text'
#cask 'tunnelbear'
cask 'visual-studio-code'
