cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'puma/puma'
tap 'homebrew/cask'

brew 'awscli'
brew 'antigen'
brew 'git'
brew 'git-flow'
brew 'go'
# brew 'grc'
brew 'hub'
# brew 'imagemagick'
brew 'jenv'
brew 'librsvg'
brew 'mkcert'
brew 'openssl'
brew 'node'
brew 'pip-completion'
brew 'python'
brew 'python3'
brew 'rbenv'
brew 'ssh-copy-id'
brew 'spaceman-diff'
brew 'tree'
brew 'watchman'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'zlib'
brew 'zsh-syntax-highlighting'

# cask '1password'
cask 'atom'
# cask 'arq'
cask 'alfred'
cask 'boostnote'
cask 'firefox'
# cask 'google-chrome'
cask 'iTerm2'
cask 'postman'
cask 'react-native-debugger'
# cask 'slack'
cask 'sourcetree'
# cask 'sublime-text'
cask 'visual-studio-code'
cask 'kaleidoscope'
